### ISSUE TITLE
result

### ISSUE THREAD

**Issue by hollow857** [jordanesikati/trait#1]
Missing function definition：seg_plant_point_cloud2 and seg_plant_point_cloud

**Comment by jordanesikati** [comment]
@hollow857 This issue was fixed recently.

**Comment by jordanesikati** [comment]
Bug fixed.

**Comment by jordanesikati** [comment]
@hollow857 Major issues have been fixed. You can play with some parameters, e.g. pcd radius, to find an optimal segmentation.
